# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9b8daaba3214e6baaaacf33f83210f7e2156c815349ff49c65adce479add3e6b7542d6d8dd057005c3a911a33b6afaaef9389ed3ab995a443f8e9d418e8e7913

test:
  secret_key_base: a08fa31b0747502de6e6e89481e806030c5529580dd6812576d5e6553423339870b84209ca2c81558e2438de556c692f740f390cacc3714b6b9c705bd189b4d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
